import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "@/components/Header/HeaderMain";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen text-white`}
      >
        <HeaderMain />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
